import React from 'react';

function rupeeFormat(n){ return Number(n).toFixed(2); }
function numToWords(n){
  // Very small helper for demo. For production use a library like 'number-to-words' or 'num-words'
  return `${n.toFixed(2)} only`;
}

export default function InvoicePreview({ client, items, totals, discountPercent, invoiceMeta }){
  const now = new Date(invoiceMeta?.date_generated || Date.now());
  const invoiceNo = invoiceMeta?.invoice_no || '(Not saved yet)';

  return (
    <div className="invoice" style={{background:'#fff', padding:20, color:'#000', width:'210mm', minHeight:'297mm', boxSizing:'border-box'}}>
      <div style={{display:'flex', justifyContent:'space-between', alignItems:'center'}}>
        <div>
          <h2 style={{margin:0}}>ABC (CHENNAI)</h2>
          <div>NO: 25, 3B 3RD FLOOR, T NAGAR, CHENNAI - 600017</div>
          <div>Tamil Nadu, India</div>
          <div>GSTIN: 33AAAAA0000A1Z5</div>
        </div>
        <div style={{textAlign:'right'}}>
          <div><strong>Invoice No:</strong> {invoiceNo}</div>
          <div><strong>Date:</strong> {now.toLocaleDateString()} {now.toLocaleTimeString()}</div>
        </div>
      </div>

      <hr />

      <div style={{display:'flex', justifyContent:'space-between', marginTop:12}}>
        <div style={{width:'60%'}}>
          <div><strong>Buyer (Bill to):</strong></div>
          <div><strong>{client.name}</strong></div>
          <div>{client.address}</div>
          <div>GSTIN: {client.gst || '—'}</div>
          <div>Phone: {client.phone || '—'}</div>
        </div>
        <div style={{width:'35%'}}>
          <div><strong>Motor Vehicle No:</strong> {client.motor_vehicle_no || '—'}</div>
          <div style={{marginTop:8}}>Other: (as per format)</div>
        </div>
      </div>

      <table className="items" style={{width:'100%', borderCollapse:'collapse', marginTop:12}}>
        <thead>
          <tr>
            <th style={{border: '1px solid #000', padding:6}}>Sl No</th>
            <th style={{border: '1px solid #000', padding:6}}>Description</th>
            <th style={{border: '1px solid #000', padding:6}}>HSN/SAC</th>
            <th style={{border: '1px solid #000', padding:6}}>No of Bags</th>
            <th style={{border: '1px solid #000', padding:6}}>Quantity (Kg)</th>
            <th style={{border: '1px solid #000', padding:6}}>Bag Qty</th>
            <th style={{border: '1px solid #000', padding:6}}>Rate/Bag</th>
            <th style={{border: '1px solid #000', padding:6}}>Rate/Kg</th>
            <th style={{border: '1px solid #000', padding:6}}>Amount</th>
          </tr>
        </thead>
        <tbody>
          {items.map((it, idx) => {
            const qtyKg = Number(it.num_bags || 0) * Number(it.bag_qty || 50);
            const amount = it.rate_per_bag ? (Number(it.rate_per_bag) * Number(it.num_bags || 0)) : (Number(it.rate_per_kg || 0) * qtyKg);
            // HSN placeholder - the HSN will be generated by backend and stored in DB when saved. Here show placeholder if not present.
            const hsn = it.hsn_sac || '—';
            return (
              <tr key={idx}>
                <td style={{border: '1px solid #000', padding:6, textAlign:'center'}}>{idx+1}</td>
                <td style={{border: '1px solid #000', padding:6}}>{it.name}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'center'}}>{hsn}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'center'}}>{it.num_bags || 0}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'right'}}>{qtyKg}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'right'}}>{it.bag_qty || 50}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'right'}}>{it.rate_per_bag ? rupeeFormat(Number(it.rate_per_bag)) : '-'}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'right'}}>{it.rate_per_kg ? rupeeFormat(Number(it.rate_per_kg)) : '-'}</td>
                <td style={{border: '1px solid #000', padding:6, textAlign:'right'}}>{rupeeFormat(amount)}</td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <div style={{display:'flex', justifyContent:'flex-end', marginTop:12}}>
        <div style={{width:300}}>
          <div style={{display:'flex', justifyContent:'space-between'}}><span>Total</span><span>{rupeeFormat(totals.total)}</span></div>
          <div style={{display:'flex', justifyContent:'space-between'}}><span>Discount ({discountPercent}%)</span><span>-{rupeeFormat(totals.discount)}</span></div>
          <div style={{display:'flex', justifyContent:'space-between', fontWeight:'bold', marginTop:6}}><span>Grand Total</span><span>{rupeeFormat(totals.grand)}</span></div>
          <div style={{marginTop:6}}>Amount (in words): {numToWords(totals.grand)}</div>
        </div>
      </div>

      <hr />

      <div style={{display:'flex', justifyContent:'space-between', marginTop:10}}>
        <div style={{width:'60%'}}>
          <div><strong>Terms & Conditions</strong></div>
          <div>Goods once sold will not be taken back. Thank you for your business.</div>
        </div>
        <div style={{width:'35%'}}>
          <div><strong>Bank Details</strong></div>
          <div>A/c Name: ABC (CHENNAI)</div>
          <div>Bank: State Bank of India</div>
          <div>IFSC: SBIN0001234</div>
          <div>Branch: T. Nagar, Chennai</div>
        </div>
      </div>
    </div>
  );
}
